<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>regx</string>
	</array>
	<key>name</key>
	<string>Regx File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#inc_comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.regx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.regx</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.regx</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Regex Name</string>
			<key>match</key>
			<string>(&lt;\[\s*)(.*?)(\s*\]&gt;)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.regx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.regx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable.parameter</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#in_regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inc_comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*def\s*$</string>
			<key>name</key>
			<string>storage.type.function.regx</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.regx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.source.regx</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.regx</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.source.python</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(def)\s+(match)(\s*|\s+([_A-Za-z][_A-Za-z0-9]*)(\s*|(\s+(\d+))))$</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>in_regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.regx</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.regx</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.regx</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\)([sSdDwWbB/])([*+?]?)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.source.regx</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.source.regx</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\)(x)</string>
				</dict>
			</array>
		</dict>
		<key>inc_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Regex Comment</string>
					<key>match</key>
					<string>-\[=\]-.*$\n?</string>
					<key>name</key>
					<string>comment.source.regx</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.regx</string>
	<key>uuid</key>
	<string>4a0dff51-a4ef-2110-9acb-9299afe1c418</string>
</dict>
</plist>
